---
- name: Install node-exporter containers and prometheus container
  hosts: all
  become: true

  tasks:
    #copy directory part
    - name: copy prometheus.yml file for worker 2.
      copy:
        src: "/home/pierre/Bureau/Quadrimestre_1/DAC/dac-tp/TP6_20.11.20/ansible/prometheus"
        dest: "/root/"
      ignore_errors: yes
      when: 
        - ansible_default_ipv4.address == "172.28.100.99"



    - name: stop and remove contgrafana
      docker_container:
        name: contgrafana
        state: absent
      when: 
        - ansible_default_ipv4.address == "172.28.100.99"

    - name: stop and remove contprometheus
      docker_container:
        name: contprometheus
        state: absent
      when: 
        - ansible_default_ipv4.address == "172.28.100.99"

    - name: stop and remove contnode_exporter
      docker_container:
        name: contnode_exporter
        state: absent

    




    - name: build contnode_exporter container for all workers
      docker_container:
        name: contnode_exporter
        image: prom/node-exporter
        # ports: 
        #   - "9100:9100"
        state: started
        volumes:
          - /:/hostfs
        network_mode: host

    - name: build contprometheus container for worker 2(172.28.100.99)
      docker_container:
        name: contprometheus
        image: prom/prometheus
        ports: 
          - "9090:9090"
        state: started
        volumes:
          - /root/prometheus/prometheus_monitoring.yml:/etc/prometheus/prometheus.yml
      when: 
        - ansible_default_ipv4.address == "172.28.100.99"

    - name: build contgrafana container for worker 2(172.28.100.99)
      docker_container:
        name: contgrafana
        image: grafana/grafana
        ports: 
          - "3000:3000"
        state: started
      when: 
        - ansible_default_ipv4.address == "172.28.100.99"

