---
- name: firewalld
  #hosts: serveurs_sans_ssh
  hosts: all
  become: true
  

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: install firewalld
      apt:
       name: firewalld
       state: present
    # ou bien d'une autre façon (avec affichage du résultat (debug):
    #   command: apt-get install firewalld
    #   register: log
    # - debug: msg="{{ log.stdout_lines }}"

    - name: Disable ssh service
      firewalld:
        #permanent permet de garder le changement meme apres un reboot
        permanent: true
        #on peut lister tous les services avec la commande #firewall-cmd --get-services
        service: ssh
        #state enabled ou disabled pour le service
        state: disabled
      #l'équivalent en commande:
      #command: firewall-cmd --remove-service=ssh
      

    - name: setup firewallD for SSH
      firewalld:
        port: 22/tcp
        state: enabled
      # NE PAS UTILISER PERMANENT !!!
      #   permanent: true
      #l'équivalent en commande:
    #   command: firewall-cmd --add-port=22/tcp
    #   register: log
    # - debug: msg="{{ log }}"

    - name: setup firewallD for HTTP
      firewalld:
        port: 80/tcp
        state: enabled

    - name: setup firewallD for HTTPS
      firewalld:
        port: 443/tcp
        state: enabled
      