scrape_configs:
- job_name: node
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  static_configs:
    # - targets: [ '192.168.1.4:9100' ]
    - targets: [ '172.28.100.111:9100', '172.28.100.99:9100', '172.28.100.51:9100', '172.28.100.19:9100' ]
      labels:
        group: 'workers_machines'

    # - targets: ['172.28.100.90:9090']
    #   labels:
    #     group: 'reverse_proxy'