scrape_configs:
- job_name: blackbox
  scrape_interval: 5s
  metrics_path: /probe
  params: 
    module: [http_2xx]

  static_configs:
    - targets: [ '172.28.100.111:8000', '172.28.100.99:8000', '172.28.100.51:8000', '172.28.100.19:8000' ]
      labels:
        group: 'workers_machines'

    - targets: [ '172.28.100.111:9080' ] 
      labels:
        group: 'load_balencer'

  #sert à faire de la string parsing. Dès qu'on a plusieurs targets, la requete ajoute un 's' a targets, ce qui perturbe prometheus
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 172.28.100.99:9115